---
version: "3.7"
volumes:
        boxfuse:
services:
        build_boxfuse:
                volumes:
                        - boxfuse:/var/boxfuse/target/
                build: build/
        prod_boxfuse:
                volumes:
                        - boxfuse:/opt/tomcat/webapps/hello
                build: prod/
                command: "/opt/tomcat/bin/catalina.sh run"
                ports:
                        - "8080:8080"
